language: php

notifications:
  email:
    - carsten@carstenwindler.de

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - |
    composer require \
      typo3/cms-backend="$TYPO3_VERSION" \
      typo3/cms-core="$TYPO3_VERSION" \
      typo3/cms-extbase="$TYPO3_VERSION" \
      typo3/cms-extensionmanager="$TYPO3_VERSION" \
      typo3/cms-fluid="$TYPO3_VERSION" \
      typo3/cms-frontend="$TYPO3_VERSION" \
      typo3/cms-install="$TYPO3_VERSION" \
      typo3/cms-scheduler="$TYPO3_VERSION" \
      typo3/cms-recordlist="$TYPO3_VERSION" \
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c Tests/Build/UnitTests.xml

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  #- >
  #  echo;
  #  export typo3DatabaseName="typo3";
  #  export typo3DatabaseHost="localhost";
  #  export typo3DatabaseUsername="root";
  #  export typo3DatabasePassword="";
  #  find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}'

  - >
    echo;
    echo "Running code sniffer";
    .Build/bin/phpcs --standard=PSR2 Classes

jobs:
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
  include:
    - stage: test
      php: 7.3
      env: TYPO3_VERSION="~9.5.0" TYPO3_UPGRADE_FROM_VERSION="~9.5.0"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="~9.5.0"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^8.7.22
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^8.7.22
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7.22